# Generated by Django 5.0 on 2024-01-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_rollno_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='rollno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='section',
        ),
    ]
